version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: youtube-thumbnail-fetcher
    container_name: youtube-thumbnail-fetcher-app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - thumbnail-fetcher
    depends_on:
      - mysql

  mysql:
    image: 'mariadb:latest'
    container_name: youtube-thumbnail-fetcher-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./database/dbdata:/var/lib/mysql
    networks:
      - thumbnail-fetcher

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: youtube-thumbnail-fetcher-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - mysql
    ports:
      - 8765:80
    networks:
      - thumbnail-fetcher

networks:
  thumbnail-fetcher:
    driver: bridge
